ALTER TABLE MEMBER DROP COLUMN LOGIN_FAILURED_COUNT;
ALTER TABLE MEMBER ADD COLUMN LOGIN_FAILURED_COUNT INT DEFAULT 0 AFTER EMAIL;
ALTER TABLE MEMBER DROP COLUMN LAST_FAILURED_AT;
ALTER TABLE MEMBER ADD COLUMN LAST_FAILURED_AT DATETIME AFTER MODIFIED_AT;
 	