CREATE TABLE MEMBER (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT
    ,LOGIN_ID VARCHAR(255)
    ,PASSWORD VARCHAR(255)
    ,SEI VARCHAR(255)
    ,MEI VARCHAR(255)
    ,TEL VARCHAR(255)
    ,EMAIL VARCHAR(255)
    ,CREATED_AT DATETIME
    ,MODIFIED_AT DATETIME
    ,DELETED_AT DATETIME
);
 